.commitlintrc.yaml
=> 🔧 OPS-105: Add jira project key WA

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 OPS-105: Add Jira project key CSY

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 OPS-105: Add Jira project key BETA

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 OPS-162: Add Jira project key DAT

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 OPS-162: Add Jira project key RA

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-002: Add Jira project key RRA
-
=> 🔧 SRE-002: Add Jira project key RRA

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-003: Add Jira project key FI
-
=> 🔧 SRE-003: Add Jira project key FI

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-004: Add Jira project key TI
-
=> 🔧 SRE-004: Add Jira project key TI

.commitlintrc.js, .commitlintrc.yaml
-  🔧 SRE-005: Add Jira project key RT
-
=> 🔧 SRE-005: Add Jira project key RT

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-006: Add Jira project key SDT
-
=> 🔧 SRE-006: Add Jira project key SDT

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-007: Add Jira project key YI
-
=> 🔧 SRE-007: Add Jira project key YI

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-008: Add Jira project key SD
-
=> 🔧 SRE-008: Add Jira project key SD

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-009: Add Jira project key EP
-
=> 🔧 SRE-009: Add Jira project key EP

.commitlintrc.js, .commitlintrc.yaml
- The label is included to identify the Task ID with the Git branch.
- The BPY board could do to match with the git commits.
=> 🔧 BPY-22: Include BPY label

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 NADM-63: Include NADM label

.commitlintrc.js, .commitlintrc.yaml
=> ✨ SC-64: Include SC Label

.commitlintrc.js, .commitlintrc.yaml
- Include the `SB` acronym for the `SOAT BCP` board and user stories.
=> 🔧 SB-1: Include the SOAT BCP task

.commitlintrc.js, .commitlintrc.yaml
- Include the `CS` acronym for the `Cyber Security` board and user stories.
=> 🔧 CS-3: Include the new board key

.commitlintrc.js, .commitlintrc.yaml
- Include the `'VYP` acronym for the `Life Insurance: Vida Yape - Pacífico` board and user stories commits.
=> 🔧 VYP-35: Include the new board key

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-010: Add Jira project key TCK
-
=> 🔧 SRE-010: Add Jira project key TCK

.commitlintrc.js, .commitlintrc.yaml
Add the new label PS for the commit linter workflow
Add the new label PS for the commit linter workflow
- Add the new label PS for the commit linter workflow
=> 🔧 PS-2: Include PS label

.commitlintrc.js, .commitlintrc.yaml
- 🔧 CR-6: Add Jira project key CR
-
=> 🔧 CR-6: Add Jira project key CR

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-010: Add Jira project key MB
=> 🔧 SRE-010: Add Jira project key MB

.commitlintrc.js, .commitlintrc.yaml
Add SPM project
-
-
**PR Summary by Typo**
------------
**Summary**
This pull request expands project keys in `.commitlintrc.js` and `.commitlintrc.yaml` for the `jira-task-id-project-key` rule, adding 'SPM'.
**Key Points**
* Updates project keys in `.commitlintrc.js` and `.commitlintrc.yaml`
* Adds 'SPM' value to existing project keys
* Applies to both JavaScript and YAML versions of the configuration files. 
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification …
=> 🔧 SPM-1: Include SPM label

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 PLAN-12: Include PLAN label

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 PPS-001: Add PPS label

.commitlintrc.js, .commitlintrc.yaml
Add tag to Monokera core jira project
=> 🔧 MC-673: Add jira tag monokera core

.github/workflows/commit-lint.yml
Fix: Update GitHub Action name for file copying
- Changed `canastro/copy-file-action@master` to `canastro/copy-action@master`
- This fixes the workflow error: "Repository not found: canastro/copy-file-action"
- Verified against the official repository: https://github.com/canastro/copy-action
This change affects commit-lint.yml in the repositories of Monokera organización on Github
-   🔧 SRE-010: Add Jira project key MB
=> 🔧 SRE-011: Update Linters Workflow on Github Actions

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-012: Add Jira project key CB
=> 🔧 SRE-012: Add Jira project key CB

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 CEP-6: Add CEP project label

.commitlintrc.js, .commitlintrc.yaml
-   🔧 SRE-14: Add New Key YAPE
=> 🔧 SRE-14: Add New Key YAPE

.commitlintrc.js, .commitlintrc.yaml
=> 🔧 SRE-15: Add New Key SALES

.commitlintrc.js, .commitlintrc.yaml
- Include the `MM` acronym for the `Mi Banco Mapfre board` and user stories commits.
-
-
=> 🔧 MM-36: Include the new board key
